### ISSUE TITLE
redshift-qt mystery instances

### ISSUE THREAD

**Issue by z3ntu** [Chemrat/redshift-qt#3]
Is there a possibility that redshift-qt is able to replicate itself after eg suspend? I have redshift-qt in my `~/.config/autostart/` folder but after some time (some hours) I have multiple redshift-qt icons in my tray... Any idea? I'm running KDE Plasma 5.9.5, maybe it has something to do with that...

**Comment by Chemrat** [comment]
Yeah, I don't think it's supposed to do that, but I haven't tried it out with suspend. I'll test it a bit later & maybe limit the amount of instances. Are those actually multiple instances (e.g. not just panel glitch showing multiple icons)? You can check it in KDE's process manager (Ctrl+Esc) or by running `ps -e | grep redshift`, you should see only one instance of `redshift` and one instance of `redshift-qt`

One thing you can do now is check your KDE session settings. In System Settings → Startup and Shutdown → Desktop Session, if you have "Restore previous session" enabled, you don't actually have to manually add redshift-qt to autostart.

**Comment by z3ntu** [comment]
I don't have the problem right now but there were multiple redshift-qt entries with different `-session` parameters.

**Comment by z3ntu** [comment]
```
luca@g550jk ~> ps -aux | grep -i redshift
luca      2693  0.0  0.2 539692 40556 ?        Sl   09:57   0:01 /usr/bin/redshift-qt -session 10d1a03530000149522888600000010610048_1495958231_928957
luca      2712  0.0  0.2 539692 39988 ?        Sl   09:57   0:01 /usr/bin/redshift-qt -session 10d1a03530000149562863100000010680009_1495958231_928961
luca      2725  0.0  0.0 288488  5096 ?        Sl   09:57   0:00 /usr/bin/redshift -v
luca      2740  0.0  0.0 288488  7024 ?        Sl   09:57   0:00 /usr/bin/redshift -v
luca      2745  0.0  0.2 539696 40568 ?        Sl   09:57   0:01 /usr/bin/redshift-qt -session 10d1a03530000149573157200000014970010_1495958231_928966
luca      2752  0.0  0.0 288484  5028 ?        Sl   09:57   0:00 /usr/bin/redshift -v
luca     20487  0.0  0.0  11104  2304 pts/0    S+   12:42   0:00 grep --color=auto -i redshift
```

**Comment by Chemrat** [comment]
Session key is passed by KDE session manager when it restores previously running session
So if you have both "Restore previous session" enabled and redshift-qt in autostart, then it might be the cause of duplicate instances. If you always use session restoration, then you can disable reshift-qt in autostart.

In any case, if you use git version, update to the latest one, it should fix the issue. Close all existing redshift-qt instances beforehand, so they won't pop up in future sessions.

**Comment by z3ntu** [comment]
I actually removed redshift-qt from the autostart before rebooting the last time and it still happened... Weird issues... But thanks for the fix/workaround 😄
