### ISSUE TITLE
Use tray icons from installed theme instead?

### ISSUE THREAD

**Issue by GUiHKX** [Chemrat/redshift-qt#4]
I'm using the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) and they have tray icons for `redshift-gtk`:

![gtk](https://user-images.githubusercontent.com/626206/27006042-7096a5de-4e01-11e7-9fd1-323be8fc715b.png)

But they don't work with `redshift-qt`:

![qt](https://user-images.githubusercontent.com/626206/27006047-76f4d838-4e01-11e7-96a2-ea9765017e41.png)

It'd be great if your program used the icons provided by an icon theme (if available)...

Thank you!

**Comment by GUiHKX** [comment]
Perhaps this code from KeePassXc can help you implement it

1. https://github.com/keepassxreboot/keepassxc/blob/a6bc3e9790050544abcfd1b04797b0aa45b1988a/src/core/FilePath.cpp#L107
1. https://github.com/keepassxreboot/keepassxc/blob/a6bc3e9790050544abcfd1b04797b0aa45b1988a/src/core/FilePath.cpp#L92

**Comment by Chemrat** [comment]
Should be implemented in latest git now
If you're not using git build, I can tag a new release

**Comment by GUiHKX** [comment]
I've just installed the git version. Looks great! Thank you

**Comment by guixxx** [comment]
Hi,

When are you planning to release the next stable version with this feature?

Thank you.

**Comment by Chemrat** [comment]
@guixxx alright, tagged a new release with this change

**Comment by guixxx** [comment]
@Chemrat Neat, thanks a bunch!
